### PR TITLE
debug output for prometheus poller metrics collection

### PR DESCRIPTION
**Pull request by freeformz**

### CODE REVIEW

**Comment by freeformz** [comment]
For helping with current and possibly future metrics collection debugging.

**Comment by freeformz** [comment]
Output example
```
agentmon: non protobuff mf mf.GetName(): jvm_threads_current
agentmon: 1 = dto.MetricType_GAUGE
agentmon: metric 0: m.GetTimestampsMs(): 0
agentmon: metric 0: m.GetGauge().String(): "value:42 "
agentmon: metric 0: m.GetGauge().GetVaue(): 42.000000
agentmon: --------------------------------------------
agentmon: non protobuff mf mf.GetName(): process_open_fds
agentmon: 1 = dto.MetricType_GAUGE
agentmon: metric 0: m.GetTimestampsMs(): 0
agentmon: metric 0: m.GetGauge().String(): "value:88 "
agentmon: metric 0: m.GetGauge().GetVaue(): 88.000000
agentmon: --------------------------------------------
agentmon: non protobuff mf mf.GetName(): process_resident_memory_bytes
agentmon: 1 = dto.MetricType_GAUGE
agentmon: metric 0: m.GetTimestampsMs(): 0
agentmon: metric 0: m.GetGauge().String(): "value:9.1787264e+07 "
agentmon: metric 0: m.GetGauge().GetVaue(): 91787264.000000
agentmon: --------------------------------------------
agentmon: non protobuff mf mf.GetName(): jvm_gc_collection_seconds
agentmon: 2 = dto.MetricType_SUMMARY
agentmon: metric 0: lp 0: GetName(): "gc" GetValue: "PS Scavenge"
agentmon: metric 0: m.GetTimestampsMs(): 0
agentmon: metric 0: m.GetSummary().String(): "sample_count:0 sample_sum:0 "
agentmon: metric 0: m.GetSummary().GetSampleCount(): 0
agentmon: metric 0: m.GetSummary().GetSampleSum(): 0.000000
agentmon: metric 1: lp 0: GetName(): "gc" GetValue: "PS MarkSweep"
agentmon: metric 1: m.GetTimestampsMs(): 0
agentmon: metric 1: m.GetSummary().String(): "sample_count:0 sample_sum:0 "
agentmon: metric 1: m.GetSummary().GetSampleCount(): 0
agentmon: metric 1: m.GetSummary().GetSampleSum(): 0.000000
agentmon: --------------------------------------------
agentmon: non protobuff mf mf.GetName(): jvm_memory_bytes_max
agentmon: 1 = dto.MetricType_GAUGE
agentmon: metric 0: lp 0: GetName(): "area" GetValue: "heap"
agentmon: metric 0: m.GetTimestampsMs(): 0
agentmon: metric 0: m.GetGauge().String(): "value:1.4318829568e+10 "
agentmon: metric 0: m.GetGauge().GetVaue(): 14318829568.000000
agentmon: metric 1: lp 0: GetName(): "area" GetValue: "nonheap"
agentmon: metric 1: m.GetTimestampsMs(): 0
agentmon: metric 1: m.GetGauge().String(): "value:-1 "
agentmon: metric 1: m.GetGauge().GetVaue(): -1.000000
agentmon: --------------------------------------------
agentmon: non protobuff mf mf.GetName(): process_cpu_seconds_total
agentmon: 0 = dto.MetricType_COUNTER
agentmon: metric 0: m.GetTimestampsMs(): 0
agentmon: metric 0: m.GetCounter().String(): "value:3.5 "
agentmon: metric 0: m.GetCounter().GetValue(): 3.500000
agentmon: --------------------------------------------
agentmon: non protobuff mf mf.GetName(): process_start_time_seconds
agentmon: 1 = dto.MetricType_GAUGE
agentmon: metric 0: m.GetTimestampsMs(): 0
agentmon: metric 0: m.GetGauge().String(): "value:1.490999584339e+09 "
agentmon: metric 0: m.GetGauge().GetVaue(): 1490999584.339000
agentmon: --------------------------------------------
agentmon: non protobuff mf mf.GetName(): process_virtual_memory_bytes
agentmon: 1 = dto.MetricType_GAUGE
agentmon: metric 0: m.GetTimestampsMs(): 0
agentmon: metric 0: m.GetGauge().String(): "value:2.2227705856e+10 "
agentmon: metric 0: m.GetGauge().GetVaue(): 22227705856.000000
agentmon: --------------------------------------------
agentmon: non protobuff mf mf.GetName(): jvm_memory_pool_bytes_used
agentmon: 1 = dto.MetricType_GAUGE
agentmon: metric 0: lp 0: GetName(): "pool" GetValue: "Code Cache"
agentmon: metric 0: m.GetTimestampsMs(): 0
agentmon: metric 0: m.GetGauge().String(): "value:4.605504e+06 "
agentmon: metric 0: m.GetGauge().GetVaue(): 4605504.000000
agentmon: metric 1: lp 0: GetName(): "pool" GetValue: "Metaspace"
agentmon: metric 1: m.GetTimestampsMs(): 0
agentmon: metric 1: m.GetGauge().String(): "value:1.5555952e+07 "
agentmon: metric 1: m.GetGauge().GetVaue(): 15555952.000000
agentmon: metric 2: lp 0: GetName(): "pool" GetValue: "Compressed Class Space"
agentmon: metric 2: m.GetTimestampsMs(): 0
agentmon: metric 2: m.GetGauge().String(): "value:1.785088e+06 "
agentmon: metric 2: m.GetGauge().GetVaue(): 1785088.000000
agentmon: metric 3: lp 0: GetName(): "pool" GetValue: "PS Eden Space"
agentmon: metric 3: m.GetTimestampsMs(): 0
agentmon: metric 3: m.GetGauge().String(): "value:2.4716152e+08 "
agentmon: metric 3: m.GetGauge().GetVaue(): 247161520.000000
agentmon: metric 4: lp 0: GetName(): "pool" GetValue: "PS Survivor Space"
agentmon: metric 4: m.GetTimestampsMs(): 0
agentmon: metric 4: m.GetGauge().String(): "value:0 "
agentmon: metric 4: m.GetGauge().GetVaue(): 0.000000
agentmon: metric 5: lp 0: GetName(): "pool" GetValue: "PS Old Gen"
agentmon: metric 5: m.GetTimestampsMs(): 0
agentmon: metric 5: m.GetGauge().String(): "value:0 "
agentmon: metric 5: m.GetGauge().GetVaue(): 0.000000
agentmon: --------------------------------------------
agentmon: non protobuff mf mf.GetName(): jvm_threads_daemon
agentmon: 1 = dto.MetricType_GAUGE
agentmon: metric 0: m.GetTimestampsMs(): 0
agentmon: metric 0: m.GetGauge().String(): "value:10 "
agentmon: metric 0: m.GetGauge().GetVaue(): 10.000000
agentmon: --------------------------------------------
agentmon: non protobuff mf mf.GetName(): jvm_threads_started_total
agentmon: 0 = dto.MetricType_COUNTER
agentmon: metric 0: m.GetTimestampsMs(): 0
agentmon: metric 0: m.GetCounter().String(): "value:50 "
agentmon: metric 0: m.GetCounter().GetValue(): 50.000000
agentmon: --------------------------------------------
agentmon: non protobuff mf mf.GetName(): jvm_memory_bytes_used
agentmon: 1 = dto.MetricType_GAUGE
agentmon: metric 0: lp 0: GetName(): "area" GetValue: "heap"
agentmon: metric 0: m.GetTimestampsMs(): 0
agentmon: metric 0: m.GetGauge().String(): "value:2.4716152e+08 "
agentmon: metric 0: m.GetGauge().GetVaue(): 247161520.000000
agentmon: metric 1: lp 0: GetName(): "area" GetValue: "nonheap"
agentmon: metric 1: m.GetTimestampsMs(): 0
agentmon: metric 1: m.GetGauge().String(): "value:2.1946544e+07 "
agentmon: metric 1: m.GetGauge().GetVaue(): 21946544.000000
agentmon: --------------------------------------------
agentmon: non protobuff mf mf.GetName(): jvm_memory_pool_bytes_committed
agentmon: 1 = dto.MetricType_GAUGE
agentmon: metric 0: lp 0: GetName(): "pool" GetValue: "Code Cache"
agentmon: metric 0: m.GetTimestampsMs(): 0
agentmon: metric 0: m.GetGauge().String(): "value:4.653056e+06 "
agentmon: metric 0: m.GetGauge().GetVaue(): 4653056.000000
agentmon: metric 1: lp 0: GetName(): "pool" GetValue: "Metaspace"
agentmon: metric 1: m.GetTimestampsMs(): 0
agentmon: metric 1: m.GetGauge().String(): "value:1.6121856e+07 "
agentmon: metric 1: m.GetGauge().GetVaue(): 16121856.000000
agentmon: metric 2: lp 0: GetName(): "pool" GetValue: "Compressed Class Space"
agentmon: metric 2: m.GetTimestampsMs(): 0
agentmon: metric 2: m.GetGauge().String(): "value:1.96608e+06 "
agentmon: metric 2: m.GetGauge().GetVaue(): 1966080.000000
agentmon: metric 3: lp 0: GetName(): "pool" GetValue: "PS Eden Space"
agentmon: metric 3: m.GetTimestampsMs(): 0
agentmon: metric 3: m.GetGauge().String(): "value:2.52182528e+08 "
agentmon: metric 3: m.GetGauge().GetVaue(): 252182528.000000
agentmon: metric 4: lp 0: GetName(): "pool" GetValue: "PS Survivor Space"
agentmon: metric 4: m.GetTimestampsMs(): 0
agentmon: metric 4: m.GetGauge().String(): "value:4.194304e+07 "
agentmon: metric 4: m.GetGauge().GetVaue(): 41943040.000000
agentmon: metric 5: lp 0: GetName(): "pool" GetValue: "PS Old Gen"
agentmon: metric 5: m.GetTimestampsMs(): 0
agentmon: metric 5: m.GetGauge().String(): "value:6.72661504e+08 "
agentmon: metric 5: m.GetGauge().GetVaue(): 672661504.000000
agentmon: --------------------------------------------
agentmon: non protobuff mf mf.GetName(): jvm_memory_pool_bytes_max
agentmon: 1 = dto.MetricType_GAUGE
agentmon: metric 0: lp 0: GetName(): "pool" GetValue: "Code Cache"
agentmon: metric 0: m.GetTimestampsMs(): 0
agentmon: metric 0: m.GetGauge().String(): "value:2.5165824e+08 "
agentmon: metric 0: m.GetGauge().GetVaue(): 251658240.000000
agentmon: metric 1: lp 0: GetName(): "pool" GetValue: "Metaspace"
agentmon: metric 1: m.GetTimestampsMs(): 0
agentmon: metric 1: m.GetGauge().String(): "value:-1 "
agentmon: metric 1: m.GetGauge().GetVaue(): -1.000000
agentmon: metric 2: lp 0: GetName(): "pool" GetValue: "Compressed Class Space"
agentmon: metric 2: m.GetTimestampsMs(): 0
agentmon: metric 2: m.GetGauge().String(): "value:1.073741824e+09 "
agentmon: metric 2: m.GetGauge().GetVaue(): 1073741824.000000
agentmon: metric 3: lp 0: GetName(): "pool" GetValue: "PS Eden Space"
agentmon: metric 3: m.GetTimestampsMs(): 0
agentmon: metric 3: m.GetGauge().String(): "value:5.285347328e+09 "
agentmon: metric 3: m.GetGauge().GetVaue(): 5285347328.000000
agentmon: metric 4: lp 0: GetName(): "pool" GetValue: "PS Survivor Space"
agentmon: metric 4: m.GetTimestampsMs(): 0
agentmon: metric 4: m.GetGauge().String(): "value:4.194304e+07 "
agentmon: metric 4: m.GetGauge().GetVaue(): 41943040.000000
agentmon: metric 5: lp 0: GetName(): "pool" GetValue: "PS Old Gen"
agentmon: metric 5: m.GetTimestampsMs(): 0
agentmon: metric 5: m.GetGauge().String(): "value:1.0738991104e+10 "
agentmon: metric 5: m.GetGauge().GetVaue(): 10738991104.000000
agentmon: --------------------------------------------
agentmon: non protobuff mf mf.GetName(): jvm_threads_peak
agentmon: 3 = dto.MetricType_UNTYPED
agentmon: metric 0: m.GetTimestampsMs(): 0
agentmon: metric 0: m.GetUntyped().String(): "value:45 "
agentmon: metric 0: m.GetUntyped().GetValue(): 45.000000
agentmon: --------------------------------------------
agentmon: non protobuff mf mf.GetName(): process_max_fds
agentmon: 1 = dto.MetricType_GAUGE
agentmon: metric 0: m.GetTimestampsMs(): 0
agentmon: metric 0: m.GetGauge().String(): "value:10000 "
agentmon: metric 0: m.GetGauge().GetVaue(): 10000.000000
agentmon: --------------------------------------------
agentmon: non protobuff mf mf.GetName(): jvm_memory_bytes_committed
agentmon: 1 = dto.MetricType_GAUGE
agentmon: metric 0: lp 0: GetName(): "area" GetValue: "heap"
agentmon: metric 0: m.GetTimestampsMs(): 0
agentmon: metric 0: m.GetGauge().String(): "value:9.66787072e+08 "
agentmon: metric 0: m.GetGauge().GetVaue(): 966787072.000000
agentmon: metric 1: lp 0: GetName(): "area" GetValue: "nonheap"
agentmon: metric 1: m.GetTimestampsMs(): 0
agentmon: metric 1: m.GetGauge().String(): "value:2.2740992e+07 "
agentmon: metric 1: m.GetGauge().GetVaue(): 22740992.000000
agentmon: --------------------------------------------
```

**Comment by apg** [comment]
@freeformz is this turned on with `-verbose` ?

**Comment by apg** [comment]
Oh, shoot. I mean `-debug`, and yeah. Obviously.

Looks good to me. Approving.

**Pull request merged**
